EMTHT/solidaris

app/models/mission.rb, db/migrate/20180820202908_create_missions.rb, db/migrate/20180820203650_add_columns_to_user.rb, db/migrate/20180820204119_add_columns_to_organization.rb, db/schema.rb, test/models/mission_test.rb
Bon deuxième partie des models!
Pour la dernière table (applications/candidatures), je la fais demain avec julie!
=> ajout model + column

app/models/organization.rb, config/environments/development.rb, config/environments/production.rb, config/initializers/devise.rb, config/routes.rb, db/migrate/20180820165122_devise_create_organizations.rb, db/schema.rb, test/models/organization_test.rb
Bon le model organizations a été créé 
Mais il faudra penser à retourner sur les configurations une fois le nom de domaine arrêté!
=> première étape de la création de model faite

app/models/application.rb, db/migrate/20180821094427_create_applications.rb, db/schema.rb, test/models/application_test.rb
=> Add application_model

app/controllers/account/profiles_controller.rb, app/controllers/associations_controller.rb, app/controllers/missions_controller.rb, app/views/associations/show.html.erb
Bon je pense que la show, l'édit et l'update fonctionne même s'il manque pas mal d'info pour le moment
=> Add css to show association

app/assets/stylesheets/components/_dashboard.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_pictures.scss, app/assets/stylesheets/components/_shows.scss, app/controllers/applications_controller.rb, app/views/account/profiles/show.html.erb, app/views/missions/show.html.erb
=> Fin back users

app/assets/stylesheets/components/_dashboard.scss, app/assets/stylesheets/components/_missions-cards.scss, app/assets/stylesheets/components/_pictures.scss, app/assets/stylesheets/components/_shows.scss, app/views/account/profiles/show.html.erb, app/views/associations/show.html.erb, app/views/layouts/application.html.erb
=> Add css to show profile asso

app/assets/stylesheets/components/_missions-cards.scss, app/views/missions/index.html.erb
=> new colors

app/controllers/missions_controller.rb, app/views/missions/index.html.erb, config/application.rb, config/locales/fr.yml
Filtres avancés
dates mises en françias
=> filtres avancés + date en français

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb, config/locales/fr.yml
La navbar de la show prend le background de la page
=> Travail sur les navbars

app/controllers/missions_controller.rb, app/views/missions/index.html.erb
pour les dates en français bis
=> fixage de bug

app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
=> no more navbar & fix div+btn

app/views/missions/show.html.erb
juste un "E" en trop, pas du tout dans les seed en plus.
=> faute d'orthographe

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_new_button.scss, app/assets/stylesheets/config/_colors.scss, app/views/pages/home.html.erb
=> buttons tests

app/assets/stylesheets/components/_new_button.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
=> Fix buttons

app/javascript/components/flatpickrcount.js, app/views/layouts/application.html.erb
=> Debut liste checkout

app/assets/stylesheets/components/_form.scss, app/views/organizations/missions/index.html.erb, app/views/organizations/missions/new.html.erb
=> Resolution page cinq cent

app/views/organizations/missions/new.html.erb
BOn cela fait moche sur mon écran classique mais ça fonctionne avec la résolution de Pierre
=> adaptation du css à l'écran

app/views/layouts/application.html.erb
Il manque une image de bonne dimension
=> ajout des tags, il manque juste à trouver l'image

app/assets/stylesheets/components/_associations_cards.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_mini_cards.scss, app/assets/stylesheets/components/_new_dashboard.scss, app/views/account/missions/index.html.erb, app/views/associations/index.html.erb, app/views/shared/_navbar.html.erb
=> Improve dashboard

app/assets/stylesheets/components/_filter.scss
=> Add z index

app/assets/stylesheets/pages/_home.scss
je ne peux pas vraiment faire de screenshot, je suis en vue adaptative
=> some padding on home page
